name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Black
        uses: psf/black@stable
        with:
          options: "--check --diff"

      - name: Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."
